# Generated by Django 6.0.5 on 2026-07-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_rename_completed_note_pinned_note_note_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklistitem",
            name="text",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
