# Generated by Django 6.0.5 on 2026-08-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_alter_checklistitem_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
